ERROR - 2022-12-13 10:45:50 --> mysqli_sql_exception: Unknown column 'cliente.Apellido' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\FacturasM.php(30): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Facturas.php(95): App\Models\FacturasM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Facturas->selectCliente('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 10:45:50 --> Call to a member function getResult() on bool
in APPPATH\Models\FacturasM.php on line 31.
 1 APPPATH\Controllers\API\Facturas.php(95): App\Models\FacturasM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Facturas->selectCliente('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-13 10:45:58 --> mysqli_sql_exception: Unknown column 'cliente.Apellido' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\FacturasM.php(30): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Facturas.php(95): App\Models\FacturasM->Relacion('2')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Facturas->selectCliente('2')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 10:45:58 --> Call to a member function getResult() on bool
in APPPATH\Models\FacturasM.php on line 31.
 1 APPPATH\Controllers\API\Facturas.php(95): App\Models\FacturasM->Relacion('2')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Facturas->selectCliente('2')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-13 10:46:46 --> mysqli_sql_exception: Unknown column 'cliente.Apellido' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\FacturasM.php(30): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Facturas.php(95): App\Models\FacturasM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Facturas->selectCliente('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 10:46:46 --> Call to a member function getResult() on bool
in APPPATH\Models\FacturasM.php on line 31.
 1 APPPATH\Controllers\API\Facturas.php(95): App\Models\FacturasM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Facturas->selectCliente('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-13 10:52:04 --> mysqli_sql_exception: Unknown column 'cliente.Apellido' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\FacturasM.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Facturas.php(95): App\Models\FacturasM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Facturas->selectCliente('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 10:52:04 --> Call to a member function getResult() on bool
in APPPATH\Models\FacturasM.php on line 32.
 1 APPPATH\Controllers\API\Facturas.php(95): App\Models\FacturasM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Facturas->selectCliente('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-13 11:01:00 --> mysqli_sql_exception: Unknown column 'cliente.Id As Nombrecli' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\FacturasM.php(32): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Facturas.php(95): App\Models\FacturasM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Facturas->selectCliente('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 11:01:00 --> Call to a member function getResult() on bool
in APPPATH\Models\FacturasM.php on line 33.
 1 APPPATH\Controllers\API\Facturas.php(95): App\Models\FacturasM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Facturas->selectCliente('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-13 11:01:07 --> mysqli_sql_exception: Unknown column 'cliente.Id As Nombrecli' in 'field list' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\FacturasM.php(32): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Facturas.php(95): App\Models\FacturasM->Relacion('2')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Facturas->selectCliente('2')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 11:01:07 --> Call to a member function getResult() on bool
in APPPATH\Models\FacturasM.php on line 33.
 1 APPPATH\Controllers\API\Facturas.php(95): App\Models\FacturasM->Relacion('2')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Facturas->selectCliente('2')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-13 11:07:23 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`cliente_Id`, `cliente`.`Id`
FROM `factura`
WHERE `cliente`.`Id` = '1'' at line 1 in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\FacturasM.php(32): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Facturas.php(95): App\Models\FacturasM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Facturas->selectCliente('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 11:07:23 --> Call to a member function getResult() on bool
in APPPATH\Models\FacturasM.php on line 33.
 1 APPPATH\Controllers\API\Facturas.php(95): App\Models\FacturasM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Facturas->selectCliente('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-13 11:16:29 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`cliente_Id`, `cliente`.`Id`
FROM `factura`
WHERE `cliente`.`Id` = '1'' at line 1 in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\FacturasM.php(32): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Facturas.php(96): App\Models\FacturasM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Facturas->selectCliente('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 11:16:29 --> Call to a member function getResult() on bool
in APPPATH\Models\FacturasM.php on line 33.
 1 APPPATH\Controllers\API\Facturas.php(96): App\Models\FacturasM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Facturas->selectCliente('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-13 11:17:37 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`cliente_Id`, `cliente`.`Id`
FROM `factura`
WHERE `cliente`.`Id` = '1'' at line 1 in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\FacturasM.php(32): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Facturas.php(96): App\Models\FacturasM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Facturas->selectCliente('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 11:17:37 --> Call to a member function getResult() on bool
in APPPATH\Models\FacturasM.php on line 33.
 1 APPPATH\Controllers\API\Facturas.php(96): App\Models\FacturasM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Facturas->selectCliente('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-13 11:18:48 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`cliente_Id`, `cliente`.`Id`
FROM `factura`
WHERE `cliente`.`Id` = '1'' at line 1 in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `cliente...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `cliente...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `cliente...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `cliente...', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\FacturasM.php(32): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Facturas.php(96): App\Models\FacturasM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Facturas->selectCliente('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 11:18:48 --> Call to a member function getResult() on bool
in APPPATH\Models\FacturasM.php on line 34.
 1 APPPATH\Controllers\API\Facturas.php(96): App\Models\FacturasM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Facturas->selectCliente('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-13 11:51:26 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`tienda`.`factura`, CONSTRAINT `factura_ibfk_1` FOREIGN KEY (`cliente_Id`) REFERENCES `cliente` (`Id`)) in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 C:\xampp\htdocs\Tienda\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Tienda\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Tienda\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Tienda\app\Controllers\API\Facturas.php(24): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Facturas->crear()
#9 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Facturas))
#10 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-13 13:55:48 --> mysqli_sql_exception: Table 'tienda.proveedor' doesn't exist in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `product...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `product...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `product...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `product...', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\ProductosM.php(33): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Productos.php(96): App\Models\ProductosM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Productos->selectProvedores('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Productos))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 13:55:48 --> Call to a member function getResult() on bool
in APPPATH\Models\ProductosM.php on line 34.
 1 APPPATH\Controllers\API\Productos.php(96): App\Models\ProductosM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Productos->selectProvedores('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Productos))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-13 13:57:20 --> mysqli_sql_exception: Table 'tienda.proveedor' doesn't exist in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `product...', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `product...')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `product...')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `product...', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\ProductosM.php(33): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Productos.php(96): App\Models\ProductosM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Productos->selectProvedores('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Productos))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 13:57:20 --> Call to a member function getResult() on bool
in APPPATH\Models\ProductosM.php on line 34.
 1 APPPATH\Controllers\API\Productos.php(96): App\Models\ProductosM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Productos->selectProvedores('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Productos))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-13 14:16:44 --> mysqli_sql_exception: Unknown column 'factura.factura_Id' in 'on clause' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `venta`....', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `venta`....')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `venta`....')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `venta`....', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\VentasM.php(33): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 14:16:44 --> Call to a member function getResult() on bool
in APPPATH\Models\VentasM.php on line 34.
 1 APPPATH\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-13 14:17:36 --> mysqli_sql_exception: Unknown column 'factura.factura_Id' in 'on clause' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `venta`....', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `venta`....')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `venta`....')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `venta`....', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\VentasM.php(33): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('10')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('10')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 14:17:36 --> Call to a member function getResult() on bool
in APPPATH\Models\VentasM.php on line 34.
 1 APPPATH\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('10')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('10')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-13 14:17:44 --> mysqli_sql_exception: Unknown column 'factura.factura_Id' in 'on clause' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `venta`....', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `venta`....')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `venta`....')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `venta`....', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\VentasM.php(33): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 14:17:44 --> Call to a member function getResult() on bool
in APPPATH\Models\VentasM.php on line 34.
 1 APPPATH\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-13 14:22:33 --> mysqli_sql_exception: Unknown column 'factura.factura_cliente_Id' in 'on clause' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `venta`....', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `venta`....')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `venta`....')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `venta`....', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\VentasM.php(33): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 14:22:33 --> Call to a member function getResult() on bool
in APPPATH\Models\VentasM.php on line 34.
 1 APPPATH\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-13 14:25:40 --> mysqli_sql_exception: Unknown column 'factura.factura_Id' in 'on clause' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `venta`....', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `venta`....')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `venta`....')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `venta`....', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\VentasM.php(33): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 14:25:40 --> Call to a member function getResult() on bool
in APPPATH\Models\VentasM.php on line 34.
 1 APPPATH\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-13 14:47:26 --> mysqli_sql_exception: Unknown column 'factura.factura_Id' in 'on clause' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `venta`....', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `venta`....')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `venta`....')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `venta`....', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\VentasM.php(33): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 14:47:26 --> Call to a member function getResult() on bool
in APPPATH\Models\VentasM.php on line 34.
 1 APPPATH\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-13 14:48:23 --> mysqli_sql_exception: Unknown column 'factura.factura_Id' in 'on clause' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `venta`....', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `venta`....')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `venta`....')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `venta`....', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\VentasM.php(33): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 14:48:23 --> Call to a member function getResult() on bool
in APPPATH\Models\VentasM.php on line 34.
 1 APPPATH\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-13 14:49:30 --> mysqli_sql_exception: Unknown column 'factura.factura_Id' in 'on clause' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `venta`....', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `venta`....')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `venta`....')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `venta`....', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\VentasM.php(33): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 14:49:30 --> Call to a member function getResult() on bool
in APPPATH\Models\VentasM.php on line 34.
 1 APPPATH\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-13 15:03:07 --> mysqli_sql_exception: Unknown column 'factura.factura_Id' in 'on clause' in C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\Tienda\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `venta`....', 0)
#1 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `venta`....')
#2 C:\xampp\htdocs\Tienda\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `venta`....')
#3 C:\xampp\htdocs\Tienda\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `venta`....', Array, false)
#4 C:\xampp\htdocs\Tienda\app\Models\VentasM.php(33): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Tienda\app\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
#6 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
#7 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
#8 C:\xampp\htdocs\Tienda\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Tienda\public\index.php(81): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Tienda\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2022-12-13 15:03:07 --> Call to a member function getResult() on bool
in APPPATH\Models\VentasM.php on line 34.
 1 APPPATH\Controllers\API\Ventas.php(95): App\Models\VentasM->Relacion('1')
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\API\Ventas->selectFacturas('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Ventas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(81): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
